To determine the year's top-trending videos, YouTube uses a combination of
factors including measuring users interactions (number of views, shares, comments and likes).Note that they’re not the most-viewed videos overall for the calendar year.

This dataset is the daily record from the top trending YouTube videos. Top 200 trending videos of a given day.

Original Data was collected during 14th November 2017 & 5th March 2018(though, data for January 10th & 11th of 2017 is missing)
Original dataset was collected by Youtube API.

Subscriber column data was scrapped on 13th March of 2018, through a automated python script.(time delay)
NA introduced in the column for videos are removed by the Youtube due to copyright or other issue.

In [1]:
#관련된 모듈 불러오기
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib as plt

In [12]:
#데이터로드
youtube = pd.read_csv("USvideos_modified.csv")
youtube.head()

,video_id,last_trending_date,publish_date,publish_hour,category_id,channel_title,views,likes,dislikes,comment_count,...,tag_appeared_in_title,title,tags,description,trend_day_count,trend.publish.diff,trend_tag_highest,trend_tag_total,tags_count,subscriber
0,2kyS6SvSYSE,2017-11-20,2017-11-13,17,22,CaseyNeistat,2564903,96321,7972,22149,...,False,WE WANT TO TALK ABOUT OUR MARRIAGE,SHANtell martin,SHANTELL'S CHANNEL - https://www.youtube.com/s...,7,7,2,2,1,9086142.0
1,1ZAPwfrtAFY,2017-11-20,2017-11-13,7,24,LastWeekTonight,6109402,151250,11508,19820,...,False,The Trump Presidency: Last Week Tonight with J...,last week tonight trump presidency|last week t...,"One year after the presidential election, John...",7,7,65,69,4,5937292.0
2,5qpjK5DgCt4,2017-11-20,2017-11-12,19,23,Rudy Mancuso,5315471,187303,7278,9990,...,True,"Racist Superman | Rudy Mancuso, King Bach & Le...",racist superman|rudy|mancuso|king|bach|racist|...,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,7,8,68,426,23,4191209.0
3,puqaWrEC7tY,2017-11-20,2017-11-13,11,24,Good Mythical Morning,913268,16729,1386,2988,...,True,Nickelback Lyrics: Real or Fake?,rhett and link|gmm|good mythical morning|rhett...,Today we find out if Link is a Nickelback amat...,7,7,488,1246,28,13186408.0
4,d380meD0W0M,2017-11-19,2017-11-12,18,24,nigahiga,2819118,153395,2416,20573,...,True,I Dare You: GOING BALD!?,ryan|higa|higatv|nigahiga|i dare you|idy|rhpc|...,I know it's been a while since we did this sho...,6,7,488,1007,14,20563106.0

In [7]:
youtube.columns

Index(['video_id', 'last_trending_date', 'publish_date', 'publish_hour',
       'category_id', 'channel_title', 'views', 'likes', 'dislikes',
       'comment_count', 'comments_disabled', 'ratings_disabled',
       'tag_appeared_in_title_count', 'tag_appeared_in_title', 'title', 'tags',
       'description', 'trend_day_count', 'trend.publish.diff',
       'trend_tag_highest', 'trend_tag_total', 'tags_count', 'subscriber'],
      dtype='object')

In [9]:
youtube.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4547 entries, 0 to 4546
Data columns (total 23 columns):
video_id                       4547 non-null object
last_trending_date             4547 non-null object
publish_date                   4547 non-null object
publish_hour                   4547 non-null int64
category_id                    4547 non-null int64
channel_title                  4547 non-null object
views                          4547 non-null int64
likes                          4547 non-null int64
dislikes                       4547 non-null int64
comment_count                  4547 non-null int64
comments_disabled              4547 non-null bool
ratings_disabled               4547 non-null bool
tag_appeared_in_title_count    4547 non-null int64
tag_appeared_in_title          4547 non-null bool
title                          4547 non-null object
tags                           4339 non-null object
description                    4458 non-null object
trend_day_count                4547 non-null int64
trend.publish.diff             4547 non-null int64
trend_tag_highest              4547 non-null int64
trend_tag_total                4547 non-null int64
tags_count                     4547 non-null int64
subscriber                     4525 non-null float64
dtypes: bool(3), float64(1), int64(12), object(7)
memory usage: 723.9+ KB

In [10]:
youtube.describe()

,publish_hour,category_id,views,likes,dislikes,comment_count,tag_appeared_in_title_count,trend_day_count,trend.publish.diff,trend_tag_highest,trend_tag_total,tags_count,subscriber
count,4547.000000,4547.000000,4.547000e+03,4.547000e+03,4.547000e+03,4.547000e+03,4547.000000,4547.000000,4547.000000,4547.000000,4547.000000,4547.000000,4.525000e+03
mean,13.503189,20.416538,1.265665e+06,3.919696e+04,2.616788e+03,4.938788e+03,2.961293,4.830658,34.429954,130.335386,437.941060,19.209369,3.164303e+06
std,6.548420,7.309226,4.526133e+06,1.419793e+05,3.662803e+04,3.110122e+04,2.482547,2.614707,247.514298,150.400756,616.584168,12.452361,4.831613e+06
min,0.000000,1.000000,5.590000e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00
25%,8.000000,17.000000,9.089650e+04,1.486000e+03,7.600000e+01,2.260000e+02,1.000000,3.000000,5.000000,22.000000,68.000000,9.000000,2.466470e+05
50%,15.000000,24.000000,3.188400e+05,7.397000e+03,2.910000e+02,8.540000e+02,3.000000,5.000000,6.000000,85.000000,217.000000,18.000000,1.198769e+06
75%,18.000000,25.000000,1.006673e+06,2.557550e+04,1.023000e+03,2.862500e+03,4.000000,7.000000,7.000000,151.000000,515.000000,29.000000,3.766915e+06
max,23.000000,43.000000,1.493761e+08,3.093544e+06,1.674420e+06,1.361580e+06,18.000000,14.000000,4215.000000,488.000000,3644.000000,69.000000,2.867694e+07

In [11]:
youtube.isnull().sum()

video_id                         0
last_trending_date               0
publish_date                     0
publish_hour                     0
category_id                      0
channel_title                    0
views                            0
likes                            0
dislikes                         0
comment_count                    0
comments_disabled                0
ratings_disabled                 0
tag_appeared_in_title_count      0
tag_appeared_in_title            0
title                            0
tags                           208
description                     89
trend_day_count                  0
trend.publish.diff               0
trend_tag_highest                0
trend_tag_total                  0
tags_count                       0
subscriber                      22
dtype: int64

### 이 kaggle given data set 은 2017년11월~2018년3월 사이의 데일리 trending video에 올라온 비디오들의 Statistics를 가져온건데, 날짜도 outdated되었고, 미국 데이터인데다가 구독자수 column 또한 뒤늦게 가져온 거라, 새로 한국데이터를 scraping하는게 낫겠다 라고 생각했습니다.
### 그래서 한국 유투브 트렌딩 비디오를 직접 일주일간 scrapping 하는 걸 제안합니다.